import type { Project } from "@/types"

const SCHOOL = "Amara Jyothi School, Mulbagal"

// Real student projects from Amara Jyothi School. Each links to the live build.
export const projects: Project[] = [
  {
    id: "chess-quest",
    slug: "chess-quest",
    title: "Chess Quest",
    builtBy: "Grade 7 students",
    grade: "Grade 7",
    gradeBand: "6-7",
    type: "tool",
    school: SCHOOL,
    summary: "A web application to learn the game of chess and play it online.",
    description:
      "Chess Quest is a web application built by Grade 7 students to help people learn chess and then play it online.",
    highlights: ["Learn chess and play online in one app", "Built by Grade 7 students", "Live on the web"],
    image: {
      src: "/projects/chess-quest.webp",
      aspectRatio: "11/5",
      placeholderLabel: "Screenshot: Chess Quest — 16:9",
      alt: "Chess Quest home screen with Learn, Practice, Play and Quiz options",
    },
    liveUrl: "https://childrens-chess-lear-68fi.bolt.host",
    featured: true,
  },
  {
    id: "website-for-education",
    slug: "website-for-education",
    title: "Website for Education",
    builtBy: "Syed, Grade 6",
    grade: "Grade 6",
    gradeBand: "6-7",
    type: "website",
    school: SCHOOL,
    summary: "Any subject and any topic, from pre-school to Grade 10.",
    description:
      "A learning website covering any subject and any topic from pre-school through Grade 10, built by Syed, a Grade 6 student.",
    highlights: ["Any subject, any topic", "Pre-school to Grade 10", "Built by a Grade 6 student"],
    image: {
      src: "/projects/website-for-education.webp",
      aspectRatio: "11/5",
      placeholderLabel: "Screenshot: Website for Education — 16:9",
      alt: "I.A.M.T Studies learning website homepage with subjects from Mathematics to Hindi",
    },
    liveUrl: "https://iamtstudies-285o90.app.builtwithrocket.new/",
    featured: true,
  },
  {
    id: "virtual-science-lab",
    slug: "virtual-science-lab",
    title: "Virtual Science Lab",
    builtBy: "Grade 7 students",
    grade: "Grade 7",
    gradeBand: "6-7",
    type: "tool",
    school: SCHOOL,
    summary: "A virtual lab to learn and do science experiments online.",
    description:
      "Virtual Science Lab lets students learn about and carry out science experiments virtually. It was built by Grade 7 students.",
    highlights: ["Do science experiments virtually", "Built by Grade 7 students", "Live on the web"],
    image: {
      src: "/projects/virtual-science-lab.webp",
      aspectRatio: "11/5",
      placeholderLabel: "Screenshot: Virtual Science Lab — 16:9",
      alt: "ScienceLab virtual lab homepage: learn science through hands-on experiments",
    },
    liveUrl: "https://virtual-science-lab-e6m4.bolt.host/",
    featured: true,
  },
  {
    id: "attendance-auto-messaging",
    slug: "attendance-management-auto-messaging",
    title: "Attendance Management System with Auto Messaging",
    builtBy: "Grade 9 students",
    grade: "Grade 9",
    gradeBand: "8-9",
    type: "tool",
    school: SCHOOL,
    summary: "An attendance management prototype with an automatic messaging system.",
    description:
      "A prototype attendance management system that includes an automatic messaging system, built by Grade 9 students.",
    highlights: ["Attendance management with auto messaging", "Working prototype", "Built by Grade 9 students"],
    image: {
      src: "/projects/attendance-management-auto-messaging.webp",
      aspectRatio: "11/5",
      placeholderLabel: "Screenshot: Attendance Management System with Auto Messaging — 16:9",
      alt: "Attendance Nexus AI dashboard showing live clock, present and absent counts and attendance rate",
    },
    liveUrl: "https://edu-aura-attendance.lovable.app",
    featured: true,
  },
  {
    id: "gatepass-management",
    slug: "gatepass-management-system",
    title: "GatePass Management System",
    builtBy: "Grade 9 students",
    grade: "Grade 9",
    gradeBand: "8-9",
    type: "tool",
    school: SCHOOL,
    summary: "A web app for the gatekeeper to manage visitor and school gate pass logs.",
    description:
      "A web app that lets the gatekeeper manage visitor logs and school gate passes, built by Grade 9 students.",
    highlights: ["Gatekeeper tool for visitor logs", "Manages school gate passes", "Built by Grade 9 students"],
    image: {
      src: "/projects/gatepass-management-system.webp",
      aspectRatio: "11/5",
      placeholderLabel: "Screenshot: GatePass Management System — 16:9",
      alt: "Nightwatch AI gate pass system for Amara Jyothi School in a dark security-console theme",
    },
    liveUrl: "https://nightwatch-ai-securi-9tdn.bolt.host/",
    featured: true,
    liveInUse: true,
  },
  {
    id: "school-website",
    slug: "school-website",
    title: "School Website",
    builtBy: "Grade 9 students",
    grade: "Grade 9",
    gradeBand: "8-9",
    type: "website",
    school: SCHOOL,
    summary: "A prototype of the school website.",
    description: "A prototype of the school's website, designed and built by Grade 9 students.",
    highlights: ["School website prototype", "Designed and built by Grade 9 students"],
    image: {
      src: "/projects/school-website.webp",
      aspectRatio: "11/5",
      placeholderLabel: "Screenshot: School Website prototype — 16:9",
      alt: "Amara Jyothi School website prototype homepage",
    },
    liveUrl: "https://school-website-proto-5xo0.bolt.host/",
    featured: true,
  },
  {
    id: "school-attendance-management",
    slug: "school-attendance-management-system",
    title: "School Attendance Management System",
    builtBy: "Grade 8 students",
    grade: "Grade 8",
    gradeBand: "8-9",
    type: "tool",
    school: SCHOOL,
    summary: "An attendance management system prototype.",
    description: "A prototype attendance management system for the school, built by Grade 8 students.",
    highlights: ["Attendance management prototype", "Built by Grade 8 students"],
    image: {
      src: "/projects/school-attendance-management-system.webp",
      aspectRatio: "11/5",
      placeholderLabel: "Screenshot: School Attendance Management System — 16:9",
      alt: "Amara Jyothi School attendance dashboard showing total teachers and today's attendance rate",
    },
    liveUrl: "https://amara-jyothi-attendance-621239.onhercules.app/",
    featured: true,
  },
]
